use Mix.Config

# Configure your database
config :dailyploy, Dailyploy.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "fbvyyirxnzprpl",
  password: "261bc38ccf4058ca69801070845a32f3dc59bdb6c3f4b462cbe30813f768a2d3",
  database: "ddrcnad8bdgsrv",
  hostname: "ec2-23-23-182-18.compute-1.amazonaws.com",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :dailyploy, DailyployWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# config :dailyploy, DailyployWeb.EmailConfig,
#   api_key: "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",
#   api_keyID: "nYWCtRLIRxC3BtlkZ3u01A"

config :sendgrid,
  api_key: System.get_env("SENDGRID_API_KEY")

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
